/**
 * shared/constants/statuses.js
 * AOBNAP — Application state machine statuses (spec §4)
 * No appeals statuses per project requirement.
 */

const APPLICATION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  AUTOMATIC_VALIDATION_FAILED: 'AUTOMATIC_VALIDATION_FAILED',
  
  // New parallel review workflow
  PARALLEL_REVIEW_PENDING: 'PARALLEL_REVIEW_PENDING', // Both offices reviewing
  REVIEWS_COMPLETED: 'REVIEWS_COMPLETED', // Both reviews done, waiting for Communication final decision
  
  // Keep old statuses for compatibility
  PERMISSION_PENDING: 'PERMISSION_PENDING',
  PERMISSION_CORRECTION_REQUIRED: 'PERMISSION_CORRECTION_REQUIRED',
  PERMISSION_REJECTED: 'PERMISSION_REJECTED',
  PERMISSION_APPROVED: 'PERMISSION_APPROVED',
  LANGUAGE_REVIEW_PENDING: 'LANGUAGE_REVIEW_PENDING',
  LANGUAGE_CORRECTION_REQUIRED: 'LANGUAGE_CORRECTION_REQUIRED',
  LANGUAGE_REJECTED: 'LANGUAGE_REJECTED',
  
  // Final statuses
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

/**
 * Valid transitions per spec §4.
 * Key = current status, Value = array of allowed next statuses.
 * Backend enforces these; frontend only reflects.
 */
const VALID_TRANSITIONS = Object.freeze({
  [APPLICATION_STATUS.DRAFT]: [APPLICATION_STATUS.SUBMITTED],
  [APPLICATION_STATUS.SUBMITTED]: [
    APPLICATION_STATUS.AUTOMATIC_VALIDATION_FAILED,
    APPLICATION_STATUS.PARALLEL_REVIEW_PENDING, // New: Communication routes to both offices
  ],
  [APPLICATION_STATUS.PARALLEL_REVIEW_PENDING]: [
    APPLICATION_STATUS.REVIEWS_COMPLETED, // Both offices completed their reviews
  ],
  [APPLICATION_STATUS.REVIEWS_COMPLETED]: [
    APPLICATION_STATUS.APPROVED, // Communication approves based on both reviews
    APPLICATION_STATUS.REJECTED, // Communication rejects based on both reviews
  ],
  // Keep old transitions for backward compatibility
  [APPLICATION_STATUS.PERMISSION_PENDING]: [
    APPLICATION_STATUS.PERMISSION_APPROVED,
    APPLICATION_STATUS.PERMISSION_REJECTED,
    APPLICATION_STATUS.PERMISSION_CORRECTION_REQUIRED,
  ],
  [APPLICATION_STATUS.PERMISSION_CORRECTION_REQUIRED]: [
    APPLICATION_STATUS.PERMISSION_PENDING,
  ],
  [APPLICATION_STATUS.PERMISSION_APPROVED]: [
    APPLICATION_STATUS.LANGUAGE_REVIEW_PENDING,
  ],
  [APPLICATION_STATUS.LANGUAGE_REVIEW_PENDING]: [
    APPLICATION_STATUS.APPROVED,
    APPLICATION_STATUS.LANGUAGE_REJECTED,
    APPLICATION_STATUS.LANGUAGE_CORRECTION_REQUIRED,
  ],
  [APPLICATION_STATUS.LANGUAGE_CORRECTION_REQUIRED]: [
    APPLICATION_STATUS.LANGUAGE_REVIEW_PENDING,
  ],
  // Terminal states — no further transitions
  [APPLICATION_STATUS.PERMISSION_REJECTED]: [],
  [APPLICATION_STATUS.LANGUAGE_REJECTED]: [],
  [APPLICATION_STATUS.APPROVED]: [],
  [APPLICATION_STATUS.REJECTED]: [],
  [APPLICATION_STATUS.AUTOMATIC_VALIDATION_FAILED]: [],
});

const TURIZM_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CORRECTION_REQUESTED: 'CORRECTION_REQUESTED',
});

const COMMERCIAL_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CORRECTION_REQUESTED: 'CORRECTION_REQUESTED',
});

// BusinessPermission status (used by Financial/Commercial officers)
const PERMISSION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CORRECTION_REQUIRED: 'CORRECTION_REQUIRED',
});

// LanguageReview status (used by Language/Turizm officers)
const LANGUAGE_REVIEW_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CORRECTION_REQUIRED: 'CORRECTION_REQUIRED',
});

const COMMUNICATION_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  ROUTED: 'ROUTED',
  REVIEW_COMPLETED: 'REVIEW_COMPLETED',
  FINALIZED: 'FINALIZED',
});

const IDENTITY_VERIFICATION_STATUS = Object.freeze({
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED',
  PENDING: 'PENDING',
});

const DOCUMENT_TYPE = Object.freeze({
  BUSINESS_PERMISSION: 'BUSINESS_PERMISSION',
  OTHER: 'OTHER',
});

const REGISTRY_SOURCE = Object.freeze({
  HISTORICAL_IMPORT: 'HISTORICAL_IMPORT',
  MANUAL_ENTRY: 'MANUAL_ENTRY',
  NEW_APPROVAL: 'NEW_APPROVAL',
});

const NOTIFICATION_TYPE = Object.freeze({
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  PERMISSION_APPROVED: 'PERMISSION_APPROVED',
  PERMISSION_REJECTED: 'PERMISSION_REJECTED',
  PERMISSION_CORRECTION_REQUIRED: 'PERMISSION_CORRECTION_REQUIRED',
  LANGUAGE_APPROVED: 'LANGUAGE_APPROVED',
  LANGUAGE_REJECTED: 'LANGUAGE_REJECTED',
  LANGUAGE_CORRECTION_REQUIRED: 'LANGUAGE_CORRECTION_REQUIRED',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  CERTIFICATE_READY: 'CERTIFICATE_READY',
  CORRECTION_SUBMITTED: 'CORRECTION_SUBMITTED',
});

/**
 * Validates if a transition from currentStatus to nextStatus is allowed.
 * @param {string} currentStatus
 * @param {string} nextStatus
 * @returns {boolean}
 */
function isValidTransition(currentStatus, nextStatus) {
  const allowed = VALID_TRANSITIONS[currentStatus];
  return Array.isArray(allowed) && allowed.includes(nextStatus);
}

module.exports = {
  APPLICATION_STATUS,
  VALID_TRANSITIONS,
  TURIZM_STATUS,
  COMMERCIAL_STATUS,
  PERMISSION_STATUS,
  LANGUAGE_REVIEW_STATUS,
  COMMUNICATION_STATUS,
  IDENTITY_VERIFICATION_STATUS,
  DOCUMENT_TYPE,
  REGISTRY_SOURCE,
  NOTIFICATION_TYPE,
  isValidTransition,
};
